### ISSUE TITLE
Прощание с дефисами и опечатки

### ISSUE THREAD

**Issue by Krethub** [FlyInk13/FlyInk13#1]
🔥 Топ проектов
Flyink — Личная группа
Callback API Бот — 160 тысяч пользователей
LiveWidget — 338 тысяч сообществ
Сниппеты историй — 25 тысяч пользователей

☠️ Топ похороненных проектов
toGraffiti — 490 тысяч установок (ВКонтакте прикрыли Граффити)
FlyVK — 176 тысяч установок (ВКонтакте стал минифицировать код)

⚓️ Где меня найти
Санкт-Петербург, ВКонтакте, Telegram, GitHub, Zenly, Instagram, Twitter, LinkedIn, dev@ifx.su

🛠 Моё вооружение
Руки, голова, JavaScript, PHP, MacOS, Git, Nginx, MySQL, MongoDB, Node.JS

**Comment by FlyInk13** [comment]
Спасибо!
